# Generated by Django 3.2 on 2021-04-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profiles_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
