# Generated by Django 3.2 on 2021-04-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
