# Generated by Django 3.2 on 2021-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_orders',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
