# Generated by Django 3.2 on 2021-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_orders_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_orders',
            name='customer_name',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
