# Generated by Django 3.2 on 2021-04-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_orders_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_orders',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='post_orders',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
