# Generated by Django 3.2 on 2021-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210425_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_orders',
            name='customer_contact',
            field=models.IntegerField(null=True),
        ),
    ]
