# Generated by Django 3.2 on 2021-06-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profiles_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_orders',
            name='Chest_Size_inch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post_orders',
            name='Qameez_length_inch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post_orders',
            name='Sleves_lengt_inch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiles_order',
            name='Chest_Size_inch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiles_order',
            name='Qameez_length_inch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiles_order',
            name='Sleves_lengt_inch',
            field=models.IntegerField(null=True),
        ),
    ]
